# Generated by Django 4.2.1 on 2023-06-05 16:32

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'heigth': 480, 'width': 480}}, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-stats-up', 'Gráfico'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-users', 'Usuários'), ('lni-cog', 'Engrenagem')], max_length=12, verbose_name='Icone'),
        ),
    ]
